FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN echo "fastapi\nuvicorn\npython-multipart" > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

EXPOSE 8005

CMD ["python", "main.py"]